//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyjb {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyjb.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The serialization stream contains no inner exceptions. 的本地化字符串。
        /// </summary>
        internal static string AggregateExceptionDeserializationFailure {
            get {
                return ResourceManager.GetString("AggregateExceptionDeserializationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At least one object must implement IComparable. 的本地化字符串。
        /// </summary>
        internal static string ArgumentImplementIComparable {
            get {
                return ResourceManager.GetString("ArgumentImplementIComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; cannot be greater than &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ArgumentMinMaxValue {
            get {
                return ResourceManager.GetString("ArgumentMinMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accept action is conflicted with Reject action. 的本地化字符串。
        /// </summary>
        internal static string ConflictingAcceptAction {
            get {
                return ResourceManager.GetString("ConflictingAcceptAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reject action is conflicted with Accept action. 的本地化字符串。
        /// </summary>
        internal static string ConflictingRejectAction {
            get {
                return ResourceManager.GetString("ConflictingRejectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not a valid value for &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ConvertInvalidValue {
            get {
                return ResourceManager.GetString("ConvertInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find constructor matchs options in type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidCacheOptions {
            get {
                return ResourceManager.GetString("InvalidCacheOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid cache type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidCacheType {
            get {
                return ResourceManager.GetString("InvalidCacheType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid cache type &apos;{0}&apos;, did not implement ICache{TKey, TValue}. 的本地化字符串。
        /// </summary>
        internal static string InvalidCacheType_ICache {
            get {
                return ResourceManager.GetString("InvalidCacheType_ICache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid lexer context &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidLexerContext {
            get {
                return ResourceManager.GetString("InvalidLexerContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From {0} to {1} is not a valid source range. 的本地化字符串。
        /// </summary>
        internal static string InvalidSourceRange {
            get {
                return ResourceManager.GetString("InvalidSourceRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two parameters can not have same name. 的本地化字符串。
        /// </summary>
        internal static string SameParameterName {
            get {
                return ResourceManager.GetString("SameParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot read from a closed SourceReader. 的本地化字符串。
        /// </summary>
        internal static string SourceReaderClosed {
            get {
                return ResourceManager.GetString("SourceReaderClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot read from a closed TextReader. 的本地化字符串。
        /// </summary>
        internal static string TextReaderClosed {
            get {
                return ResourceManager.GetString("TextReaderClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unrecognized token &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedToken {
            get {
                return ResourceManager.GetString("UnrecognizedToken", resourceCulture);
            }
        }
    }
}
