//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyjb {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyjb.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ---&gt; (Inner Exception #{0}) {1} &lt;--- 的本地化字符串。
        /// </summary>
        internal static string AggregateSourceException_InnerException {
            get {
                return ResourceManager.GetString("AggregateSourceException_InnerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More than one field is found with the specified name and matching the specified binding constraints. 的本地化字符串。
        /// </summary>
        internal static string AmbiguousMatchField {
            get {
                return ResourceManager.GetString("AmbiguousMatchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More than one method is found with the specified name and matching the specified binding constraints. 的本地化字符串。
        /// </summary>
        internal static string AmbiguousMatchMethod {
            get {
                return ResourceManager.GetString("AmbiguousMatchMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More than one property is found with the specified name and matching the specified binding constraints. 的本地化字符串。
        /// </summary>
        internal static string AmbiguousMatchProperty {
            get {
                return ResourceManager.GetString("AmbiguousMatchProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ambiguous user-defined converter found when convert &apos;{0}&apos; to &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string AmbiguousUserDefinedConverter {
            get {
                return ResourceManager.GetString("AmbiguousUserDefinedConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value of parameter &apos;{0}&apos; and &apos;{1}&apos; can not botn be null. 的本地化字符串。
        /// </summary>
        internal static string ArgumentBothNull {
            get {
                return ResourceManager.GetString("ArgumentBothNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter values must be greater than zero. 的本地化字符串。
        /// </summary>
        internal static string ArgumentMustBePositive {
            get {
                return ResourceManager.GetString("ArgumentMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter values can not be negative. 的本地化字符串。
        /// </summary>
        internal static string ArgumentNegative {
            get {
                return ResourceManager.GetString("ArgumentNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter values was out of range. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter values must be between &apos;{0}&apos; and &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ArgumentOutOfRangeBetween {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter value is not a valid type. 的本地化字符串。
        /// </summary>
        internal static string ArgumentWrongType {
            get {
                return ResourceManager.GetString("ArgumentWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter value &apos;{0}&apos; is not of type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ArgumentWrongType_Specific {
            get {
                return ResourceManager.GetString("ArgumentWrongType_Specific", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The lower bound of array must be zero. 的本地化字符串。
        /// </summary>
        internal static string ArrayNonZeroLowerBound {
            get {
                return ResourceManager.GetString("ArrayNonZeroLowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Destination array is not long enough, check array index and length. 的本地化字符串。
        /// </summary>
        internal static string ArrayTooSmall {
            get {
                return ResourceManager.GetString("ArrayTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   At 的本地化字符串。
        /// </summary>
        internal static string AtText {
            get {
                return ResourceManager.GetString("AtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot bind to open constructed method. 的本地化字符串。
        /// </summary>
        internal static string BindOpenConstructedMethod {
            get {
                return ResourceManager.GetString("BindOpenConstructedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot bind to the target field because its type is not compatible with that of the delegate type. 的本地化字符串。
        /// </summary>
        internal static string BindTargetField {
            get {
                return ResourceManager.GetString("BindTargetField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot bind to the target method because its signature is not compatible with that of the delegate type. 的本地化字符串。
        /// </summary>
        internal static string BindTargetMethod {
            get {
                return ResourceManager.GetString("BindTargetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot bind to the target property because its signature is not compatible with that of the delegate type. 的本地化字符串。
        /// </summary>
        internal static string BindTargetProperty {
            get {
                return ResourceManager.GetString("BindTargetProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot bind to the target property because no get accessor exists. 的本地化字符串。
        /// </summary>
        internal static string BindTargetPropertyNoGet {
            get {
                return ResourceManager.GetString("BindTargetPropertyNoGet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot bind to the target property because no set accessor exists. 的本地化字符串。
        /// </summary>
        internal static string BindTargetPropertyNoSet {
            get {
                return ResourceManager.GetString("BindTargetPropertyNoSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 null cannot be converted to a value type. 的本地化字符串。
        /// </summary>
        internal static string CannotCastNullToValueType {
            get {
                return ResourceManager.GetString("CannotCastNullToValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not infer type argument from parameters. 的本地化字符串。
        /// </summary>
        internal static string CannotInferenceGenericArguments {
            get {
                return ResourceManager.GetString("CannotInferenceGenericArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection element count must be the same as current colection. 的本地化字符串。
        /// </summary>
        internal static string CollectionCountDiffer {
            get {
                return ResourceManager.GetString("CollectionCountDiffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection may not be empty. 的本地化字符串。
        /// </summary>
        internal static string CollectionEmpty {
            get {
                return ResourceManager.GetString("CollectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection was of a fixed size. 的本地化字符串。
        /// </summary>
        internal static string CollectionFixedSize {
            get {
                return ResourceManager.GetString("CollectionFixedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to compare two elements in the collection. 的本地化字符串。
        /// </summary>
        internal static string CollectionItemCompareFailed {
            get {
                return ResourceManager.GetString("CollectionItemCompareFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified item does not exist in collection. 的本地化字符串。
        /// </summary>
        internal static string CollectionItemNotExist {
            get {
                return ResourceManager.GetString("CollectionItemNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An element of collection was null. 的本地化字符串。
        /// </summary>
        internal static string CollectionItemNull {
            get {
                return ResourceManager.GetString("CollectionItemNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection is read-only. 的本地化字符串。
        /// </summary>
        internal static string CollectionReadOnly {
            get {
                return ResourceManager.GetString("CollectionReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delegate type &apos;{0}&apos; not compatible with &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string DelegateIncompatible {
            get {
                return ResourceManager.GetString("DelegateIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A parameter with the same name has already existed. 的本地化字符串。
        /// </summary>
        internal static string DuplicateName {
            get {
                return ResourceManager.GetString("DuplicateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection was modified, enumeration operation may not execute. 的本地化字符串。
        /// </summary>
        internal static string EnumerationFailed {
            get {
                return ResourceManager.GetString("EnumerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The argument type &apos;{0}&apos; is not the same as the enum type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string EnumTypeDoesNotMatch {
            get {
                return ResourceManager.GetString("EnumTypeDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Requested value &apos;{1}&apos; was not found in enum type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string EnumValueNotFound {
            get {
                return ResourceManager.GetString("EnumValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Error]  的本地化字符串。
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Additional non-parsable characters are at the end of the string. 的本地化字符串。
        /// </summary>
        internal static string ExtraJunkAtEnd {
            get {
                return ResourceManager.GetString("ExtraJunkAtEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base is not between 2 and 36. 的本地化字符串。
        /// </summary>
        internal static string InvalidBase {
            get {
                return ResourceManager.GetString("InvalidBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find constructor matchs options in type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidCacheOptions {
            get {
                return ResourceManager.GetString("InvalidCacheOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid cache type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidCacheType {
            get {
                return ResourceManager.GetString("InvalidCacheType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid cache type &apos;{0}&apos;, did not implement ICache{TKey, TValue}. 的本地化字符串。
        /// </summary>
        internal static string InvalidCacheType_ICache {
            get {
                return ResourceManager.GetString("InvalidCacheType_ICache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified cast is not valid. 的本地化字符串。
        /// </summary>
        internal static string InvalidCast {
            get {
                return ResourceManager.GetString("InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid cast from &apos;{0}&apos; to &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string InvalidCast_FromTo {
            get {
                return ResourceManager.GetString("InvalidCast_FromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target element type is not compatible with the type of items in the collection. 的本地化字符串。
        /// </summary>
        internal static string InvalidElementType {
            get {
                return ResourceManager.GetString("InvalidElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset and length were out of bounds for the collection. 的本地化字符串。
        /// </summary>
        internal static string InvalidOffsetLength {
            get {
                return ResourceManager.GetString("InvalidOffsetLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified threshold is out of range. 的本地化字符串。
        /// </summary>
        internal static string InvalidThreshold {
            get {
                return ResourceManager.GetString("InvalidThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An item with the same key has already been added. 的本地化字符串。
        /// </summary>
        internal static string KeyDuplicate {
            get {
                return ResourceManager.GetString("KeyDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specific key is not exists. 的本地化字符串。
        /// </summary>
        internal static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key &apos;{0}&apos; is not exists. 的本地化字符串。
        /// </summary>
        internal static string KeyNotFound_Key {
            get {
                return ResourceManager.GetString("KeyNotFound_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specified method is not supported. 的本地化字符串。
        /// </summary>
        internal static string MethodNotSupported {
            get {
                return ResourceManager.GetString("MethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only single-dimensional arrays are supported. 的本地化字符串。
        /// </summary>
        internal static string MultidimensionalArrayNotSupported {
            get {
                return ResourceManager.GetString("MultidimensionalArrayNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only single-dimensional arrays are supported of parameter &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string MultidimensionalArrayNotSupported_Param {
            get {
                return ResourceManager.GetString("MultidimensionalArrayNotSupported_Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type must derive from Delegate. 的本地化字符串。
        /// </summary>
        internal static string MustBeDelegate {
            get {
                return ResourceManager.GetString("MustBeDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; must derive from Delegate. 的本地化字符串。
        /// </summary>
        internal static string MustBeDelegate_Type {
            get {
                return ResourceManager.GetString("MustBeDelegate_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type must be an Enum. 的本地化字符串。
        /// </summary>
        internal static string MustBeEnum {
            get {
                return ResourceManager.GetString("MustBeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; must be an Enum. 的本地化字符串。
        /// </summary>
        internal static string MustBeEnum_Type {
            get {
                return ResourceManager.GetString("MustBeEnum_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must specify valid information for parsing in the string. 的本地化字符串。
        /// </summary>
        internal static string MustContainValidInfo {
            get {
                return ResourceManager.GetString("MustContainValidInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Named parameter array cannot be bigger than argument array. 的本地化字符串。
        /// </summary>
        internal static string NamedParamTooBig {
            get {
                return ResourceManager.GetString("NamedParamTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not a generic method definition. 的本地化字符串。
        /// </summary>
        internal static string NeedGenericMethodDefinition {
            get {
                return ResourceManager.GetString("NeedGenericMethodDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The string was being parsed as an unsigned number and could not have a negative sign. 的本地化字符串。
        /// </summary>
        internal static string NegativeUnsigned {
            get {
                return ResourceManager.GetString("NegativeUnsigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find any recognizable digits. 的本地化字符串。
        /// </summary>
        internal static string NoParsibleDigits {
            get {
                return ResourceManager.GetString("NoParsibleDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The object has been disposed. 的本地化字符串。
        /// </summary>
        internal static string ObjectDisposed {
            get {
                return ResourceManager.GetString("ObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One or more errors existed. 的本地化字符串。
        /// </summary>
        internal static string OneOrMoreErrorsExisted {
            get {
                return ResourceManager.GetString("OneOrMoreErrorsExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value was either too large or too small for a Byte. 的本地化字符串。
        /// </summary>
        internal static string OverflowByte {
            get {
                return ResourceManager.GetString("OverflowByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value was either too large or too small for an Int16. 的本地化字符串。
        /// </summary>
        internal static string OverflowInt16 {
            get {
                return ResourceManager.GetString("OverflowInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value was either too large or too small for an Int32. 的本地化字符串。
        /// </summary>
        internal static string OverflowInt32 {
            get {
                return ResourceManager.GetString("OverflowInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value was either too large or too small for an Int64. 的本地化字符串。
        /// </summary>
        internal static string OverflowInt64 {
            get {
                return ResourceManager.GetString("OverflowInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value was either too large or too small for a SByte. 的本地化字符串。
        /// </summary>
        internal static string OverflowSByte {
            get {
                return ResourceManager.GetString("OverflowSByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value was either too large or too small for a UInt16. 的本地化字符串。
        /// </summary>
        internal static string OverflowUInt16 {
            get {
                return ResourceManager.GetString("OverflowUInt16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value was either too large or too small for a UInt32. 的本地化字符串。
        /// </summary>
        internal static string OverflowUInt32 {
            get {
                return ResourceManager.GetString("OverflowUInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value was either too large or too small for a UInt64. 的本地化字符串。
        /// </summary>
        internal static string OverflowUInt64 {
            get {
                return ResourceManager.GetString("OverflowUInt64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More than one key parameter is found of processors. 的本地化字符串。
        /// </summary>
        internal static string ProcessorKeyAmbigus {
            get {
                return ResourceManager.GetString("ProcessorKeyAmbigus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 More than one key parameter is found of processors identified &apos;{1}&apos; of type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ProcessorKeyAmbigus_TypeId {
            get {
                return ResourceManager.GetString("ProcessorKeyAmbigus_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key parameter of processors not found. 的本地化字符串。
        /// </summary>
        internal static string ProcessorKeyNotFound {
            get {
                return ResourceManager.GetString("ProcessorKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key parameter of processors identified &apos;{1}&apos; of type &apos;{0}&apos; not found. 的本地化字符串。
        /// </summary>
        internal static string ProcessorKeyNotFound_TypeId {
            get {
                return ResourceManager.GetString("ProcessorKeyNotFound_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processor identified &apos;{1}&apos; of type &apos;{0}&apos;, does not match the needed static / instance. 的本地化字符串。
        /// </summary>
        internal static string ProcessorMismatch {
            get {
                return ResourceManager.GetString("ProcessorMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Existing static and instance method in processors identified &apos;{1}&apos; of type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ProcessorMixed {
            get {
                return ResourceManager.GetString("ProcessorMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find processor of type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ProcessorNotFound {
            get {
                return ResourceManager.GetString("ProcessorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not find processor identified &apos;{1}&apos; of type &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string ProcessorNotFound_Id {
            get {
                return ResourceManager.GetString("ProcessorNotFound_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processors have different parameter length or parameter type. 的本地化字符串。
        /// </summary>
        internal static string ProcessorParameterMismatch {
            get {
                return ResourceManager.GetString("ProcessorParameterMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processors identified &apos;{1}&apos; of type &apos;{0}&apos; have different parameter length or parameter type. 的本地化字符串。
        /// </summary>
        internal static string ProcessorParameterMismatch_TypeId {
            get {
                return ResourceManager.GetString("ProcessorParameterMismatch_TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property &apos;{0}&apos; has no get accessor exists. 的本地化字符串。
        /// </summary>
        internal static string PropertyNoGetter {
            get {
                return ResourceManager.GetString("PropertyNoGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property &apos;{0}&apos; has no set accessor exists. 的本地化字符串。
        /// </summary>
        internal static string PropertyNoSetter {
            get {
                return ResourceManager.GetString("PropertyNoSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Public property or field named &apos;{0}&apos; not exists. 的本地化字符串。
        /// </summary>
        internal static string PropertyOrFieldNotFound {
            get {
                return ResourceManager.GetString("PropertyOrFieldNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Property or field named &apos;{0}&apos; not exists. 的本地化字符串。
        /// </summary>
        internal static string PropertyOrFieldNotFound_NonPublic {
            get {
                return ResourceManager.GetString("PropertyOrFieldNotFound_NonPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameter &apos;{0}&apos; and &apos;{1}&apos; in reverse order. 的本地化字符串。
        /// </summary>
        internal static string ReversedArgument {
            get {
                return ResourceManager.GetString("ReversedArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot read from a closed &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        internal static string StreamClosed {
            get {
                return ResourceManager.GetString("StreamClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expecting non-empty string. 的本地化字符串。
        /// </summary>
        internal static string StringEmpty {
            get {
                return ResourceManager.GetString("StringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expecting non-whitespace string. 的本地化字符串。
        /// </summary>
        internal static string StringWhiteSpace {
            get {
                return ResourceManager.GetString("StringWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 False 的本地化字符串。
        /// </summary>
        internal static string Tristate_False {
            get {
                return ResourceManager.GetString("Tristate_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotSure 的本地化字符串。
        /// </summary>
        internal static string Tristate_NotSure {
            get {
                return ResourceManager.GetString("Tristate_NotSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 True 的本地化字符串。
        /// </summary>
        internal static string Tristate_True {
            get {
                return ResourceManager.GetString("Tristate_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; contains generic parameters. 的本地化字符串。
        /// </summary>
        internal static string TypeContainsGenericParameters {
            get {
                return ResourceManager.GetString("TypeContainsGenericParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type member &apos;{0}&apos; not exists. 的本地化字符串。
        /// </summary>
        internal static string TypeMemberNotFound {
            get {
                return ResourceManager.GetString("TypeMemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type &apos;{0}&apos; does not have a default constructor. 的本地化字符串。
        /// </summary>
        internal static string TypeMissingDefaultConstructor {
            get {
                return ResourceManager.GetString("TypeMissingDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true. 的本地化字符串。
        /// </summary>
        internal static string UnboundGenParam {
            get {
                return ResourceManager.GetString("UnboundGenParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Ambig] 的本地化字符串。
        /// </summary>
        internal static string UniqueValue_Ambig {
            get {
                return ResourceManager.GetString("UniqueValue_Ambig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Empty] 的本地化字符串。
        /// </summary>
        internal static string UniqueValue_Empty {
            get {
                return ResourceManager.GetString("UniqueValue_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Unique {0}] 的本地化字符串。
        /// </summary>
        internal static string UniqueValue_Unique {
            get {
                return ResourceManager.GetString("UniqueValue_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Warning]  的本地化字符串。
        /// </summary>
        internal static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
    }
}
