//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyjb {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cyjb.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 One or more errors existed. 的本地化字符串。
        /// </summary>
        internal static string AggregateSourceException_DefaultMessage {
            get {
                return ResourceManager.GetString("AggregateSourceException_DefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ---&gt; (Inner Exception #{0}) {1} &lt;--- 的本地化字符串。
        /// </summary>
        internal static string AggregateSourceException_ToString {
            get {
                return ResourceManager.GetString("AggregateSourceException_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   At 的本地化字符串。
        /// </summary>
        internal static string AtText {
            get {
                return ResourceManager.GetString("AtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Error]  的本地化字符串。
        /// </summary>
        internal static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 False 的本地化字符串。
        /// </summary>
        internal static string Tristate_False {
            get {
                return ResourceManager.GetString("Tristate_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotSure 的本地化字符串。
        /// </summary>
        internal static string Tristate_NotSure {
            get {
                return ResourceManager.GetString("Tristate_NotSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 True 的本地化字符串。
        /// </summary>
        internal static string Tristate_True {
            get {
                return ResourceManager.GetString("Tristate_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Ambig] 的本地化字符串。
        /// </summary>
        internal static string UniqueValue_Ambig {
            get {
                return ResourceManager.GetString("UniqueValue_Ambig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Empty] 的本地化字符串。
        /// </summary>
        internal static string UniqueValue_Empty {
            get {
                return ResourceManager.GetString("UniqueValue_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Unique {0}] 的本地化字符串。
        /// </summary>
        internal static string UniqueValue_Unique {
            get {
                return ResourceManager.GetString("UniqueValue_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Warning]  的本地化字符串。
        /// </summary>
        internal static string WarningText {
            get {
                return ResourceManager.GetString("WarningText", resourceCulture);
            }
        }
    }
}
