//------------------------------------------------------------------------------
// <auto-generated>
// 此代码由工具生成。
//
// 对此文件的更改可能会导致不正确的行为，并且如果
// 重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cyjb;

using ComponentModel = global::System.ComponentModel;
using ResourceManager = global::System.Resources.ResourceManager;
using CultureInfo = global::System.Globalization.CultureInfo;

/// <summary>
/// 一个强类型的资源类，用于查找本地化的字符串等。
/// </summary>
/// <remarks>此类是由 T4 文本模板通过 Visual Studio 的工具自动生成的。
/// 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 T4 模板。
/// </remarks>
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
internal partial class Resources
{
	#nullable enable

	private static ResourceManager? resourceManager;
	private static CultureInfo? resourceCulture;

	/// <summary>
	/// 获取此类使用的缓存的 <see cref="ResourceManager"/> 实例。
	/// </summary>
	[ComponentModel.EditorBrowsable(ComponentModel.EditorBrowsableState.Advanced)]
	internal static ResourceManager ResourceManager
	{
		get
		{
			if (resourceManager is null)
			{
				resourceManager = new ResourceManager("Cyjb.Resources", typeof(Resources).Assembly);
			}
			return resourceManager;
		}
	}

	/// <summary>
	/// 获取或设置资源使用的区域信息。
	/// </summary>
	[ComponentModel.EditorBrowsable(ComponentModel.EditorBrowsableState.Advanced)]
	internal static CultureInfo? Culture
	{
		get
		{
			return resourceCulture;
		}
		set
		{
			resourceCulture = value;
		}
	}
	
	/// <summary>
	/// 返回类似 <c>More than one field is found with the specified name and matching the specified binding constraints.</c> 的本地化字符串。
	/// </summary>
	internal static string AmbiguousMatchField => ResourceManager.GetString("AmbiguousMatchField", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>More than one method is found with the specified name and matching the specified binding constraints.</c> 的本地化字符串。
	/// </summary>
	internal static string AmbiguousMatchMethod => ResourceManager.GetString("AmbiguousMatchMethod", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>More than one property is found with the specified name and matching the specified binding constraints.</c> 的本地化字符串。
	/// </summary>
	internal static string AmbiguousMatchProperty => ResourceManager.GetString("AmbiguousMatchProperty", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>'{0}' cannot be greater than '{1}'.</c> 的本地化字符串。
	/// </summary>
	internal static string ArgumentMinMaxValue(object? arg0, object? arg1)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("ArgumentMinMaxValue", resourceCulture)!, Format(arg0), Format(arg1));
	}
	
	/// <summary>
	/// 返回类似 <c>'{0}' must be greater than zero.</c> 的本地化字符串。
	/// </summary>
	internal static string ArgumentMustBePositive(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("ArgumentMustBePositive", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>'{0}' can not be negative.</c> 的本地化字符串。
	/// </summary>
	internal static string ArgumentNegative(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("ArgumentNegative", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>'{0}' out of range.</c> 的本地化字符串。
	/// </summary>
	internal static string ArgumentOutOfRange(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("ArgumentOutOfRange", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>'{0}' must be between '{1}' and '{2}'.</c> 的本地化字符串。
	/// </summary>
	internal static string ArgumentOutOfRangeBetween(object? arg0, object? arg1, object? arg2)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("ArgumentOutOfRange_Between", resourceCulture)!, Format(arg0), Format(arg1), Format(arg2));
	}
	
	/// <summary>
	/// 返回类似 <c>Count must be positive and count must refer to a location within the string/array/collection.</c> 的本地化字符串。
	/// </summary>
	internal static string ArgumentOutOfRangeCount => ResourceManager.GetString("ArgumentOutOfRange_Count", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Index was out of range. Must be non-negative and less than the size of the collection.</c> 的本地化字符串。
	/// </summary>
	internal static string ArgumentOutOfRangeIndex => ResourceManager.GetString("ArgumentOutOfRange_Index", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>The parameter value '{0}' is not of type '{1}'.</c> 的本地化字符串。
	/// </summary>
	internal static string ArgumentWrongType(object? arg0, object? arg1)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("ArgumentWrongType", resourceCulture)!, Format(arg0), Format(arg1));
	}
	
	/// <summary>
	/// 返回类似 <c>The lower bound of array must be zero.</c> 的本地化字符串。
	/// </summary>
	internal static string ArrayNonZeroLowerBound => ResourceManager.GetString("ArrayNonZeroLowerBound", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Destination array is not long enough, check array index and length.</c> 的本地化字符串。
	/// </summary>
	internal static string ArrayTooSmall => ResourceManager.GetString("ArrayTooSmall", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>null cannot be converted to a value type.</c> 的本地化字符串。
	/// </summary>
	internal static string CannotCastNullToValueType => ResourceManager.GetString("CannotCastNullToValueType", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Can not infer type argument from parameters.</c> 的本地化字符串。
	/// </summary>
	internal static string CannotInferenceGenericArguments => ResourceManager.GetString("CannotInferenceGenericArguments", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Collection element count must be the same as current colection.</c> 的本地化字符串。
	/// </summary>
	internal static string CollectionCountDiffer => ResourceManager.GetString("CollectionCountDiffer", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>'{0}' may not be empty.</c> 的本地化字符串。
	/// </summary>
	internal static string CollectionEmpty(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("CollectionEmpty", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Failed to compare two elements in the collection.</c> 的本地化字符串。
	/// </summary>
	internal static string CollectionItemCompareFailed => ResourceManager.GetString("CollectionItemCompareFailed", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>An element of '{0}' was null.</c> 的本地化字符串。
	/// </summary>
	internal static string CollectionItemNull(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("CollectionItemNull", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Collection is read-only.</c> 的本地化字符串。
	/// </summary>
	internal static string CollectionReadOnly => ResourceManager.GetString("CollectionReadOnly", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>A parameter with the same name has already existed.</c> 的本地化字符串。
	/// </summary>
	internal static string DuplicateName => ResourceManager.GetString("DuplicateName", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Queue empty.</c> 的本地化字符串。
	/// </summary>
	internal static string EmptyQueue => ResourceManager.GetString("EmptyQueue", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Stack empty.</c> 的本地化字符串。
	/// </summary>
	internal static string EmptyStack => ResourceManager.GetString("EmptyStack", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Enumeration already finished.</c> 的本地化字符串。
	/// </summary>
	internal static string EnumEnded => ResourceManager.GetString("EnumEnded", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Collection was modified after the enumerator was instantiated.</c> 的本地化字符串。
	/// </summary>
	internal static string EnumFailedVersion => ResourceManager.GetString("EnumFailedVersion", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Enumeration has not started. Call MoveNext.</c> 的本地化字符串。
	/// </summary>
	internal static string EnumNotStarted => ResourceManager.GetString("EnumNotStarted", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Additional non-parsable characters are at the end of the string.</c> 的本地化字符串。
	/// </summary>
	internal static string ExtraJunkAtEnd => ResourceManager.GetString("ExtraJunkAtEnd", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Base is not between 2 and 36.</c> 的本地化字符串。
	/// </summary>
	internal static string InvalidBase => ResourceManager.GetString("InvalidBase", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Invalid cast from '{0}' to '{1}'.</c> 的本地化字符串。
	/// </summary>
	internal static string InvalidCast(object? arg0, object? arg1)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("InvalidCast", resourceCulture)!, Format(arg0), Format(arg1));
	}
	
	/// <summary>
	/// 返回类似 <c>Target element type is not compatible with the type of items in the collection.</c> 的本地化字符串。
	/// </summary>
	internal static string InvalidElementType => ResourceManager.GetString("InvalidElementType", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>The specified threshold is out of range.</c> 的本地化字符串。
	/// </summary>
	internal static string InvalidThreshold => ResourceManager.GetString("InvalidThreshold", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Invalid UnicodeCategory name.</c> 的本地化字符串。
	/// </summary>
	internal static string InvalidUnicodeCategoryName => ResourceManager.GetString("InvalidUnicodeCategoryName", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Specified method is not supported.</c> 的本地化字符串。
	/// </summary>
	internal static string MethodNotSupported => ResourceManager.GetString("MethodNotSupported", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Only single-dimensional arrays are supported.</c> 的本地化字符串。
	/// </summary>
	internal static string MultidimensionalArrayNotSupported => ResourceManager.GetString("MultidimensionalArrayNotSupported", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Only single-dimensional arrays are supported of parameter '{0}'.</c> 的本地化字符串。
	/// </summary>
	internal static string MultidimensionalArrayNotSupportedParam(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("MultidimensionalArrayNotSupported_Param", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Type '{0}' must derive from Delegate.</c> 的本地化字符串。
	/// </summary>
	internal static string MustBeDelegate(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("MustBeDelegate", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Type must be an Enum.</c> 的本地化字符串。
	/// </summary>
	internal static string MustBeEnum => ResourceManager.GetString("MustBeEnum", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Type '{0}' must be an Enum.</c> 的本地化字符串。
	/// </summary>
	internal static string MustBeEnumType(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("MustBeEnum_Type", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Must specify valid information for parsing in the string.</c> 的本地化字符串。
	/// </summary>
	internal static string MustContainValidInfo => ResourceManager.GetString("MustContainValidInfo", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Named parameter array cannot be bigger than argument array.</c> 的本地化字符串。
	/// </summary>
	internal static string NamedParamTooBig => ResourceManager.GetString("NamedParamTooBig", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>'{0}' is not a generic method definition.</c> 的本地化字符串。
	/// </summary>
	internal static string NeedGenericMethodDefinition(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("NeedGenericMethodDefinition", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>The string was being parsed as an unsigned number and could not have a negative sign.</c> 的本地化字符串。
	/// </summary>
	internal static string NegativeUnsigned => ResourceManager.GetString("NegativeUnsigned", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Could not find any recognizable digits.</c> 的本地化字符串。
	/// </summary>
	internal static string NoParsibleDigits => ResourceManager.GetString("NoParsibleDigits", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Value was either too large or too small for a Byte.</c> 的本地化字符串。
	/// </summary>
	internal static string OverflowByte => ResourceManager.GetString("OverflowByte", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Value was either too large or too small for a Int16.</c> 的本地化字符串。
	/// </summary>
	internal static string OverflowInt16 => ResourceManager.GetString("OverflowInt16", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Value was either too large or too small for a Int32.</c> 的本地化字符串。
	/// </summary>
	internal static string OverflowInt32 => ResourceManager.GetString("OverflowInt32", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Value was either too large or too small for a Int64.</c> 的本地化字符串。
	/// </summary>
	internal static string OverflowInt64 => ResourceManager.GetString("OverflowInt64", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Value was either too large or too small for a SByte.</c> 的本地化字符串。
	/// </summary>
	internal static string OverflowSByte => ResourceManager.GetString("OverflowSByte", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Value was either too large or too small for a UInt16.</c> 的本地化字符串。
	/// </summary>
	internal static string OverflowUInt16 => ResourceManager.GetString("OverflowUInt16", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Value was either too large or too small for a UInt32.</c> 的本地化字符串。
	/// </summary>
	internal static string OverflowUInt32 => ResourceManager.GetString("OverflowUInt32", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Value was either too large or too small for a UInt64.</c> 的本地化字符串。
	/// </summary>
	internal static string OverflowUInt64 => ResourceManager.GetString("OverflowUInt64", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Cannot read from a closed '{0}'.</c> 的本地化字符串。
	/// </summary>
	internal static string StreamClosed(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("StreamClosed", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Type '{0}' contains generic parameters.</c> 的本地化字符串。
	/// </summary>
	internal static string TypeContainsGenericParameters(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("TypeContainsGenericParameters", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Type '{0}' does not have a default constructor.</c> 的本地化字符串。
	/// </summary>
	internal static string TypeMissingDefaultConstructor(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("TypeMissingDefaultConstructor", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true.</c> 的本地化字符串。
	/// </summary>
	internal static string UnboundGenParam => ResourceManager.GetString("UnboundGenParam", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>[Ambig]</c> 的本地化字符串。
	/// </summary>
	internal static string UniqueValueAmbig => ResourceManager.GetString("UniqueValue_Ambig", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>[Empty]</c> 的本地化字符串。
	/// </summary>
	internal static string UniqueValueEmpty => ResourceManager.GetString("UniqueValue_Empty", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>[Unique {0}]</c> 的本地化字符串。
	/// </summary>
	internal static string UniqueValueUnique(object? arg0)
	{
		return string.Format(resourceCulture, ResourceManager.GetString("UniqueValue_Unique", resourceCulture)!, Format(arg0));
	}
	
	/// <summary>
	/// 返回类似 <c>UnorderedHashCode is a mutable struct and should not be compared with other UnorderedHashCode.</c> 的本地化字符串。
	/// </summary>
	internal static string UnorderedHashCodeEqualityNotSupported => ResourceManager.GetString("UnorderedHashCode_EqualityNotSupported", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>UnorderedHashCode is a mutable struct and should not be compared with other UnorderedHashCode.Use ToHashCode to retrieve the computed hash code.</c> 的本地化字符串。
	/// </summary>
	internal static string UnorderedHashCodeHashCodeNotSupported => ResourceManager.GetString("UnorderedHashCode_HashCodeNotSupported", resourceCulture)!;
	
	/// <summary>
	/// 返回类似 <c>Code supposed to be unreachable.</c> 的本地化字符串。
	/// </summary>
	internal static string Unreachable => ResourceManager.GetString("Unreachable", resourceCulture)!;
	
	/// <summary>
	/// 将指定对象格式化为字符串。
	/// </summary>
	/// <param name="value">要格式化的对象。</param>
	private static object Format(object? value)
	{
		if (value == null)
		{
			return "(null)";
		}
		return value;
	}

	#nullable restore

}


